# Use the official nginx image as the base image
FROM nginx:alpine

# Copy the HTML file into the container at /usr/share/nginx/html
COPY appversion1/index.html /usr/share/nginx/html/

# Expose port 80 for HTTP
EXPOSE 80