apiVersion: v1
kind: Service
metadata:
  labels:
    app: rollingupdate
  name: rollingupdate
  namespace: dev
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: rollingupdate
status:
  loadBalancer: {}
